---
#
# Ansible managed
#
repository:
  description: Manage ssh public key authentication (public / private / authorized keys and known hosts) in Debian-like systems
  homepage: https://buluma.github.io/
  topics: system, networking, ansible, molecule, tox, playbook, hacktoberfest
