---
roles:
  - name: buluma.bootstrap
  - name: buluma.core_dependencies
  - name: buluma.openssl
  - name: buluma.buildtools
  - name: buluma.epel
  - name: buluma.python_pip
collections:
  - name: ansible.posix
  - name: community.crypto
