---
roles:
  - name: buluma.bootstrap
  - name: buluma.core_dependencies
  - name: buluma.ca_certificates
  - name: buluma.openssl
  - name: buluma.pip
  - name: buluma.setuptools
collections:
  - name: ansible.posix
  - name: community.crypto
