---
- name: prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: buluma.bootstrap
    - role: buluma.openssl
    - role: buluma.core_dependencies

  collections:
    - name: ansible.posix
    - name: community.crypto
