---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  vars:
    ansible_python_interpreter: /bin/python3
  
  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.openssl

