---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: buluma.bootstrap
    - role: buluma.core_dependencies
    - role: buluma.openssl
      vars:
        ansible_python_interpreter: /usr/bin/python3
