---
name: Release
'on':
  push:
    tags:
      - '*'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Publish to Galaxy
        uses: buluma/galaxy-action@v1.0.3
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: master
